# Primeiros passos

In [ ]:
# Instalei o kagglehub no terminal (pip install kagglehub)
# Importei o kagglehub

import kagglehub
from kagglehub import KaggleDatasetAdapter

In [ ]:
# Importei as bibliotecas que conheço e creio que posso precisar

import pandas as pd
import os
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
# Fiz a leitura do arquivo csv com pandas
# Fiz o download do csv Kaggle e salvei no meu computador


df_varejo = pd.read_csv("Base Varejo.csv")

df_varejo

       DATA;CO_ID;CL_ID;CL_GENERO;CL_EC;CL_FHL;CL_SEG;PR_ID;PR_CAT;PR_NOME;;;;
0       01/02/2019;1000;534;M;4;1;C;67;BEBIDAS;REFRIGE...
1       01/02/2019;1000;534;M;4;1;C;70;BEBIDAS;REFRIGE...
2       01/02/2019;1000;534;M;4;1;C;178;HIGIENE;LENCO ...
3       01/02/2019;1000;534;M;4;1;C;4;ALIMENTOS;ABACAX...
4       01/02/2019;1000;534;M;4;1;C;175;LIMPEZA;LIMPAD...
...                                                   ...
829995  19/08/2022;919822;155;F;2;0;B;183;ALIMENTOS;KE...
829996  19/08/2022;919822;155;F;2;0;B;56;ALIMENTOS;QUE...
829997  19/08/2022;919822;155;F;2;0;B;227;ALIMENTOS;AR...
829998  19/08/2022;919822;155;F;2;0;B;214;ALIMENTOS;CE...
829999  19/08/2022;919822;155;F;2;0;B;59;ALIMENTOS;SAL...

[830000 rows x 1 columns]

In [47]:
# Organizei os dados dentro da tabela

df_varejo = pd.read_csv("Base Varejo.csv", sep = ";")

df_varejo

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP,NaN,NaN,NaN,NaN
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA,NaN,NaN,NaN,NaN
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ,NaN,NaN,NaN,NaN
829998,19/08/2022,919822,155,F,2,0,B,214,ALIMENTOS,CEBOLA,NaN,NaN,NaN,NaN
829999,19/08/2022,919822,155,F,2,0,B,59,ALIMENTOS,SALGADINHO,NaN,NaN,NaN,NaN

# Fiz um README
# Fiz um reposítório do GitHub e comecei a dar commits

In [ ]:
# Visualizei as informações do DataFrame

df_varejo.info()

<class 'pandas.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  str
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  str
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  str
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  str
 9   PR_NOME      830000 non-null  str
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), str(5)
memory usage: 88.7 MB

In [ ]:
# Verifiquei as 5 primeiras linhas do DataFrame

df_varejo.head()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

In [ ]:
# Verifiquei as últimas 5 linhas do DataFrame

df_varejo. tail()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP,NaN,NaN,NaN,NaN
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA,NaN,NaN,NaN,NaN
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ,NaN,NaN,NaN,NaN
829998,19/08/2022,919822,155,F,2,0,B,214,ALIMENTOS,CEBOLA,NaN,NaN,NaN,NaN
829999,19/08/2022,919822,155,F,2,0,B,59,ALIMENTOS,SALGADINHO,NaN,NaN,NaN,NaN

In [ ]:
# Verifiquei 5 linhas aleatórias dentro do DataFrame

df_varejo.sample(5)

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
505106,27/04/2021,556280,276,F,3,0,B,189,ALIMENTOS,GRANOLA,NaN,NaN,NaN,NaN
779398,18/06/2022,866041,955,F,3,2,C,14,ALIMENTOS,BATATA,NaN,NaN,NaN,NaN
436338,21/01/2021,479960,936,F,3,2,B,172,LIMPEZA,LUSTRA MOVEIS,NaN,NaN,NaN,NaN
187122,16/12/2019,210651,735,F,4,0,B,185,LIMPEZA,INSETICIDA,NaN,NaN,NaN,NaN
408580,14/12/2020,449364,187,M,2,1,B,6,ALIMENTOS,ALHO,NaN,NaN,NaN,NaN

In [ ]:
# Verifiquei o tamanho do DataFrame

df_varejo.shape

(830000, 14)

In [ ]:
# Verifiquei os nomes das colunas

df_varejo.columns

for i in df_varejo.columns:
    print(i)

DATA
CO_ID
CL_ID
CL_GENERO
CL_EC
CL_FHL
CL_SEG
PR_ID
PR_CAT
PR_NOME
Unnamed: 10
Unnamed: 11
Unnamed: 12
Unnamed: 13

In [58]:
# Verifiqueia coluna "filhos"

df_varejo[["CL_FHL"]]

        CL_FHL
0            1
1            1
2            1
3            1
4            1
...        ...
829995       0
829996       0
829997       0
829998       0
829999       0

[830000 rows x 1 columns]

# Limpeza de dados

In [ ]:
# Criei uma cópia do csv

df_varejo_limpo = df_varejo.copy()

In [ ]:
# Renommei as colunas

df_varejo_limpo = df_varejo_limpo.rename(columns={
    "DATA": "data",
    "CO_ID": "ID_compra",
    "CL_ID": "ID_cliente",
    "CL_GENERO": "genero_cliente",
    "CL_EC": "estado_civil",
    "CL_FHL": "numero_filhos",
    "CL_SEG": "classe_economica",
    "PR_ID": "codigo_produto",
    "PR_CAT": "categoria_produto",
    "PR_NOME": "nome_produto"
})

# Verifiquei

df_varejo_limpo.head()

,data,ID_compra,ID_cliente,genero_cliente,estado_civil,numero_filhos,classe_economica,codigo_produto,categoria_produto,nome_produto,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

In [ ]:
# Verifiquei então se todas as colunas estavam corretas

print(df_varejo_limpo.columns.tolist())

['data', 'ID_compra', 'ID_cliente', 'genero_cliente', 'estado_civil', 'numero_filhos', 'classe_economica', 'codigo_produto', 'categoria_produto', 'nome_produto', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']

In [ ]:
# Verifiquei os valores ausentes

df_varejo_limpo.isna()

,data,ID_compra,ID_cliente,genero_cliente,estado_civil,numero_filhos,classe_economica,codigo_produto,categoria_produto,nome_produto,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,False,False,False,False,False,False,False,False,False,False,True,True,True,True
1,False,False,False,False,False,False,False,False,False,False,True,True,True,True
2,False,False,False,False,False,False,False,False,False,False,True,True,True,True
3,False,False,False,False,False,False,False,False,False,False,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
829995,False,False,False,False,False,False,False,False,False,False,True,True,True,True
829996,False,False,False,False,False,False,False,False,False,False,True,True,True,True
829997,False,False,False,False,False,False,False,False,False,False,True,True,True,True
829998,False,False,False,False,False,False,False,False,False,False,True,True,True,True
829999,False,False,False,False,False,False,False,False,False,False,True,True,True,True

In [64]:
# Verifiquei todas (all) as colunas vazias (isna) e criei uma variável (colunas_vazia) para armazenar esses resultados

colunas_vazias = df_varejo_limpo.columns[df_varejo_limpo.isna().all()]

# Imprimi a contagem (len) e o nome das colunas vazias

print("Total de colunas vazias: ", len(colunas_vazias))
print("\nNomes das colunas vazias: ")

#Por fim, pedi para listar essas colunas

print(colunas_vazias.tolist())

Total de colunas vazias:  4

Nomes das colunas vazias:
['Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']

In [65]:
# Removi as colunas totalmente vazias

df_varejo_limpo = df_varejo_limpo.dropna(axis=1, how="all")

#Verifiquei as colunas restantes
print(df_varejo_limpo.columns.tolist())

['data', 'ID_compra', 'ID_cliente', 'genero_cliente', 'estado_civil', 'numero_filhos', 'classe_economica', 'codigo_produto', 'categoria_produto', 'nome_produto']

In [ ]:
# Conferi o tamanho do DataFrame após a limpeza das colunas, deu certo

df_varejo_limpo.shape

(830000, 10)

In [68]:
# Conferi novamente os valores ausentes no DataFrame

df_varejo_limpo.isna()

,data,ID_compra,ID_cliente,genero_cliente,estado_civil,numero_filhos,classe_economica,codigo_produto,categoria_produto,nome_produto
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
829995,False,False,False,False,False,False,False,False,False,False
829996,False,False,False,False,False,False,False,False,False,False
829997,False,False,False,False,False,False,False,False,False,False
829998,False,False,False,False,False,False,False,False,False,False
829999,False,False,False,False,False,False,False,False,False,False

In [ ]:
# Na dúvida, verifiquei se havia valores ausentes em alguma outra coluna do DataFrame

df_varejo_limpo.isna().sum()

data                 0
ID_compra            0
ID_cliente           0
genero_cliente       0
estado_civil         0
numero_filhos        0
classe_economica     0
codigo_produto       0
categoria_produto    0
nome_produto         0
dtype: int64

In [ ]:
# Verifiquei duplicatas no DataFrame completo

df_varejo_limpo[
    df_varejo_limpo.duplicated(keep=False)
]

,data,ID_compra,ID_cliente,genero_cliente,estado_civil,numero_filhos,classe_economica,codigo_produto,categoria_produto,nome_produto
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
7,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE
14,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA
15,01/02/2019,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE
19,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA
...,...,...,...,...,...,...,...,...,...,...
829989,19/08/2022,919822,155,F,2,0,B,34,ALIMENTOS,KETCHUP
829992,19/08/2022,919822,155,F,2,0,B,30,ALIMENTOS,FILE DE PEIXE
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ

In [71]:
# Resolvi verificar registros duplicados na coluna "ID_compra"

df_varejo_limpo["ID_compra"].duplicated().sum()

np.int64(811529)

In [ ]:
# Na dúvida se eram registros duplicados ou compras com o mesmo ID achei melhor conferir por linha
# keep=False conta a primeira ocorrência e as repetições, pode haver mais que 96.553

df_varejo_limpo.duplicated().sum()

np.int64(96553)

In [80]:
# Criei variáveis para armazenar os valores duplicados ou únicos
# Separei as linhas duplicadas para análise

mascara_duplicadas = df_varejo_limpo.duplicated(keep=False)

linhas_duplicadas = df_varejo_limpo[mascara_duplicadas].copy()

print("Linhas duplicadas: ", len(linhas_duplicadas))
print("Linhas únicas: ", len(df_varejo_limpo.drop_duplicates()))

Linhas duplicadas:  184330
Linhas únicas:  733447

In [84]:
display(linhas_duplicadas)

,data,ID_compra,ID_cliente,genero_cliente,estado_civil,numero_filhos,classe_economica,codigo_produto,categoria_produto,nome_produto
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
7,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE
14,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA
15,01/02/2019,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE
19,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA
...,...,...,...,...,...,...,...,...,...,...
829989,19/08/2022,919822,155,F,2,0,B,34,ALIMENTOS,KETCHUP
829992,19/08/2022,919822,155,F,2,0,B,30,ALIMENTOS,FILE DE PEIXE
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ

In [ ]:
# Usei a lógica (if/else) para preencher categorias vazias com "Sem Categoria"

In [ ]:
# Conferi se ainda havia ausentes e duplicatas

In [ ]:
# Com os dados melhor organizados, verifiquei os tipos de dados do DataFrame

df_varejo_limpo

dtype

In [ ]:
# Ajustei os tipos de dados e verifiquei inconsistêcias

In [ ]:
 # Validei a regra do identificador de número de compra, convertendo a string de data da compra utilizando o módulo datetime

 datetime

 #Gerar estatísticas descritivas básicas para coluna de número de filhos do cliente (média; mediana; desvio padrão; moda; máximo; mínimo; e contagem, quartis)

#Explorar padrões de agrupamento com pelo menos dois agrupamentos (por exemplo: gênero com mais vendas, compras), usando groupby() ou pivot_table().