# Primeiros passos

In [175]:
# Instalei o kagglehub no terminal (pip install kagglehub)
# Importei o kagglehub

import kagglehub

In [ ]:
# Importei a biblioteca pandas

import pandas as pd

In [177]:
# Fiz a leitura do arquivo csv com pandas
# Fiz o download do csv Kaggle e salvei no meu computador


df_varejo = pd.read_csv("Base Varejo.csv")

df_varejo

       DATA;CO_ID;CL_ID;CL_GENERO;CL_EC;CL_FHL;CL_SEG;PR_ID;PR_CAT;PR_NOME;;;;
0       01/02/2019;1000;534;M;4;1;C;67;BEBIDAS;REFRIGE...
1       01/02/2019;1000;534;M;4;1;C;70;BEBIDAS;REFRIGE...
2       01/02/2019;1000;534;M;4;1;C;178;HIGIENE;LENCO ...
3       01/02/2019;1000;534;M;4;1;C;4;ALIMENTOS;ABACAX...
4       01/02/2019;1000;534;M;4;1;C;175;LIMPEZA;LIMPAD...
...                                                   ...
829995  19/08/2022;919822;155;F;2;0;B;183;ALIMENTOS;KE...
829996  19/08/2022;919822;155;F;2;0;B;56;ALIMENTOS;QUE...
829997  19/08/2022;919822;155;F;2;0;B;227;ALIMENTOS;AR...
829998  19/08/2022;919822;155;F;2;0;B;214;ALIMENTOS;CE...
829999  19/08/2022;919822;155;F;2;0;B;59;ALIMENTOS;SAL...

[830000 rows x 1 columns]

In [178]:
# Organizei os dados dentro da tabela

df_varejo = pd.read_csv("Base Varejo.csv", sep = ";")

df_varejo

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP,NaN,NaN,NaN,NaN
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA,NaN,NaN,NaN,NaN
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ,NaN,NaN,NaN,NaN
829998,19/08/2022,919822,155,F,2,0,B,214,ALIMENTOS,CEBOLA,NaN,NaN,NaN,NaN
829999,19/08/2022,919822,155,F,2,0,B,59,ALIMENTOS,SALGADINHO,NaN,NaN,NaN,NaN

In [179]:
# Visualizei as informações do DataFrame

df_varejo.info()

<class 'pandas.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  str
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  str
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  str
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  str
 9   PR_NOME      830000 non-null  str
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), str(5)
memory usage: 88.7 MB

In [180]:
# Verifiquei as 5 primeiras linhas do DataFrame

df_varejo.head()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

In [181]:
# Verifiquei as últimas 5 linhas do DataFrame

df_varejo. tail()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP,NaN,NaN,NaN,NaN
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA,NaN,NaN,NaN,NaN
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ,NaN,NaN,NaN,NaN
829998,19/08/2022,919822,155,F,2,0,B,214,ALIMENTOS,CEBOLA,NaN,NaN,NaN,NaN
829999,19/08/2022,919822,155,F,2,0,B,59,ALIMENTOS,SALGADINHO,NaN,NaN,NaN,NaN

In [182]:
# Verifiquei 5 linhas aleatórias dentro do DataFrame

df_varejo.sample(5)

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
357854,21/09/2020,394640,84,F,3,0,C,159,ALIMENTOS,PAO DE FORMA,NaN,NaN,NaN,NaN
372648,18/10/2020,410423,463,M,3,3,B,109,LIMPEZA,RODO,NaN,NaN,NaN,NaN
165536,20/10/2019,186518,291,F,3,0,C,145,PET,RACAO UMIDA PARA GATOS,NaN,NaN,NaN,NaN
706497,03/12/2022,785619,701,M,3,0,B,36,ALIMENTOS,LATA DE MILHO,NaN,NaN,NaN,NaN
156891,10/05/2019,176531,643,F,4,0,C,169,ALIMENTOS,MAMAO,NaN,NaN,NaN,NaN

In [183]:
# Verifiquei o tamanho do DataFrame

df_varejo.shape

(830000, 14)

In [184]:
# Verifiquei os nomes das colunas

df_varejo.columns

for i in df_varejo.columns:
    print(i)

DATA
CO_ID
CL_ID
CL_GENERO
CL_EC
CL_FHL
CL_SEG
PR_ID
PR_CAT
PR_NOME
Unnamed: 10
Unnamed: 11
Unnamed: 12
Unnamed: 13

In [185]:
# Verifiqueia coluna "filhos"

df_varejo[["CL_FHL"]]

        CL_FHL
0            1
1            1
2            1
3            1
4            1
...        ...
829995       0
829996       0
829997       0
829998       0
829999       0

[830000 rows x 1 columns]

# Limpeza de dados

In [186]:
# Criei uma cópia do csv

df_varejo_limpo = df_varejo.copy()

In [187]:
# Renommei as colunas

df_varejo_limpo = df_varejo_limpo.rename(columns={
    "DATA": "data",
    "CO_ID": "ID_compra",
    "CL_ID": "ID_cliente",
    "CL_GENERO": "genero_cliente",
    "CL_EC": "estado_civil",
    "CL_FHL": "numero_filhos",
    "CL_SEG": "classe_economica",
    "PR_ID": "codigo_produto",
    "PR_CAT": "categoria_produto",
    "PR_NOME": "nome_produto"
})

# Verifiquei

df_varejo_limpo.head()

,data,ID_compra,ID_cliente,genero_cliente,estado_civil,numero_filhos,classe_economica,codigo_produto,categoria_produto,nome_produto,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

In [188]:
# Verifiquei então se todas as colunas estavam corretas

print(df_varejo_limpo.columns.tolist())

['data', 'ID_compra', 'ID_cliente', 'genero_cliente', 'estado_civil', 'numero_filhos', 'classe_economica', 'codigo_produto', 'categoria_produto', 'nome_produto', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']

In [189]:
# Verifiquei os valores ausentes

df_varejo_limpo.isna()

,data,ID_compra,ID_cliente,genero_cliente,estado_civil,numero_filhos,classe_economica,codigo_produto,categoria_produto,nome_produto,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,False,False,False,False,False,False,False,False,False,False,True,True,True,True
1,False,False,False,False,False,False,False,False,False,False,True,True,True,True
2,False,False,False,False,False,False,False,False,False,False,True,True,True,True
3,False,False,False,False,False,False,False,False,False,False,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
829995,False,False,False,False,False,False,False,False,False,False,True,True,True,True
829996,False,False,False,False,False,False,False,False,False,False,True,True,True,True
829997,False,False,False,False,False,False,False,False,False,False,True,True,True,True
829998,False,False,False,False,False,False,False,False,False,False,True,True,True,True
829999,False,False,False,False,False,False,False,False,False,False,True,True,True,True

In [190]:
# Verifiquei todas (all) as colunas vazias (isna) e criei uma variável (colunas_vazia) para armazenar esses resultados

colunas_vazias = df_varejo_limpo.columns[df_varejo_limpo.isna().all()]

# Imprimi a contagem (len) e o nome das colunas vazias

print("Total de colunas vazias: ", len(colunas_vazias))
print("\nNomes das colunas vazias: ")

#Por fim, pedi para listar essas colunas

print(colunas_vazias.tolist())

Total de colunas vazias:  4

Nomes das colunas vazias:
['Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']

In [191]:
# Removi as colunas totalmente vazias

df_varejo_limpo = df_varejo_limpo.dropna(axis=1, how="all")

#Verifiquei as colunas restantes
print(df_varejo_limpo.columns.tolist())

['data', 'ID_compra', 'ID_cliente', 'genero_cliente', 'estado_civil', 'numero_filhos', 'classe_economica', 'codigo_produto', 'categoria_produto', 'nome_produto']

In [192]:
# Conferi o tamanho do DataFrame após a limpeza das colunas, deu certo

df_varejo_limpo.shape

(830000, 10)

In [193]:
# Conferi novamente os valores ausentes no DataFrame, pareceu tudo certo

df_varejo_limpo.isna()

,data,ID_compra,ID_cliente,genero_cliente,estado_civil,numero_filhos,classe_economica,codigo_produto,categoria_produto,nome_produto
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
829995,False,False,False,False,False,False,False,False,False,False
829996,False,False,False,False,False,False,False,False,False,False
829997,False,False,False,False,False,False,False,False,False,False
829998,False,False,False,False,False,False,False,False,False,False
829999,False,False,False,False,False,False,False,False,False,False

In [194]:
# Para ter certeza absoluta, verifiquei se havia valores ausentes em alguma outra coluna do DataFrame

df_varejo_limpo.isna().sum()

data                 0
ID_compra            0
ID_cliente           0
genero_cliente       0
estado_civil         0
numero_filhos        0
classe_economica     0
codigo_produto       0
categoria_produto    0
nome_produto         0
dtype: int64

In [195]:
# Verifiquei duplicatas no DataFrame completo

df_varejo_limpo[
    df_varejo_limpo.duplicated(keep=False)
]

,data,ID_compra,ID_cliente,genero_cliente,estado_civil,numero_filhos,classe_economica,codigo_produto,categoria_produto,nome_produto
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
7,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE
14,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA
15,01/02/2019,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE
19,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA
...,...,...,...,...,...,...,...,...,...,...
829989,19/08/2022,919822,155,F,2,0,B,34,ALIMENTOS,KETCHUP
829992,19/08/2022,919822,155,F,2,0,B,30,ALIMENTOS,FILE DE PEIXE
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ

In [196]:
# Resolvi verificar registros duplicados na coluna "ID_compra"

df_varejo_limpo["ID_compra"].duplicated().sum()

np.int64(811529)

In [197]:
# Resolvi verificar registros duplicados nas colunas "data", "ID_compra", "ID_cliente" e "nome_produto"

df_varejo_limpo.duplicated(
    subset=["data", "ID_compra", "ID_cliente", "nome_produto"]).sum()

np.int64(176327)

In [198]:
print(df_varejo_limpo.columns.tolist())

['data', 'ID_compra', 'ID_cliente', 'genero_cliente', 'estado_civil', 'numero_filhos', 'classe_economica', 'codigo_produto', 'categoria_produto', 'nome_produto']

In [199]:
# Resolvi verificar registros duplicados nas colunas "data", "ID_compra", "ID_cliente", "genero_cliente", "estado_civil", "numero_filhos", "classe_economica", "codigo_produto", "categoria_produto" e "nome_produto"

df_varejo_limpo.duplicated(
    subset=["data", "ID_compra", "ID_cliente", "genero_cliente", "estado_civil", "numero_filhos", "classe_economica", "codigo_produto", "categoria_produto", "nome_produto"]).sum()

np.int64(96553)

In [200]:
# Resolvi verificar registros duplicados nas colunas "data", "ID_compra", "ID_cliente" sem "nome_produto"

df_varejo_limpo.duplicated(
    subset=["data", "ID_compra", "ID_cliente"]).sum()

np.int64(811529)

In [201]:
# Criei variáveis para armazenar os valores duplicados ou únicos
# Separei as linhas duplicadas para análise

mascara_duplicadas = df_varejo_limpo.duplicated(keep=False)

linhas_duplicadas = df_varejo_limpo[mascara_duplicadas].copy()

print("Linhas duplicadas: ", len(linhas_duplicadas))
print("Linhas únicas: ", len(df_varejo_limpo.drop_duplicates()))

Linhas duplicadas:  184330
Linhas únicas:  733447

In [202]:
# Não consegui entender/resolver, pedi ajuda para o professor e colegas

display(linhas_duplicadas)

,data,ID_compra,ID_cliente,genero_cliente,estado_civil,numero_filhos,classe_economica,codigo_produto,categoria_produto,nome_produto
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
7,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE
14,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA
15,01/02/2019,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE
19,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA
...,...,...,...,...,...,...,...,...,...,...
829989,19/08/2022,919822,155,F,2,0,B,34,ALIMENTOS,KETCHUP
829992,19/08/2022,919822,155,F,2,0,B,30,ALIMENTOS,FILE DE PEIXE
829995,19/08/2022,919822,155,F,2,0,B,183,ALIMENTOS,KETCHUP
829996,19/08/2022,919822,155,F,2,0,B,56,ALIMENTOS,QUEIJO MUSSARELA
829997,19/08/2022,919822,155,F,2,0,B,227,ALIMENTOS,ARROZ

In [ ]:
# Pedi a lista das colunas com tolist()

print(df_varejo_limpo.columns.tolist())

['data', 'ID_compra', 'ID_cliente', 'genero_cliente', 'estado_civil', 'numero_filhos', 'classe_economica', 'codigo_produto', 'categoria_produto', 'nome_produto']

In [ ]:
# Pedi a lista de nomes únicos dos produtos com nunique()

df_varejo_limpo["nome_produto"].nunique()

118

In [ ]:
# Removi os registros duplicados com drop_duplicates()

df_varejo_limpo = df_varejo_limpo.drop_duplicates()

In [ ]:
# Verifiquei a soma dos valores vazios com isna()

df_varejo_limpo["categoria_produto"].isna().sum()

np.int64(0)

In [ ]:
# Pedi uma amostra de 50 linhas para verificar a categoria dos produtos

df_varejo_limpo["categoria_produto"].sample(50)

15005      ALIMENTOS
556849     ALIMENTOS
41601      ALIMENTOS
730878     ALIMENTOS
447742     ALIMENTOS
267317     ALIMENTOS
551252     ALIMENTOS
13243        LIMPEZA
708342       LIMPEZA
218767       LIMPEZA
127146     ALIMENTOS
671887    ACESSORIOS
606749     ALIMENTOS
250263     ALIMENTOS
107750       HIGIENE
19467        LIMPEZA
627998       HIGIENE
175668       HIGIENE
612745     ALIMENTOS
576974     ALIMENTOS
778292       LIMPEZA
396113     ALIMENTOS
64897        LIMPEZA
240096     ALIMENTOS
77041        LIMPEZA
655849       HIGIENE
751107       LIMPEZA
353190           PET
384236     ALIMENTOS
272379     ALIMENTOS
695768       LIMPEZA
485719       HIGIENE
403886       HIGIENE
464598       HIGIENE
688426     ALIMENTOS
799272     ALIMENTOS
573037       LIMPEZA
151268     ALIMENTOS
576917    ACESSORIOS
645364     ALIMENTOS
783602       HIGIENE
319317       LIMPEZA
283802     ALIMENTOS
61193        HIGIENE
139053       HIGIENE
154345       HIGIENE
765923     ALIMENTOS
311095       LIMPEZA
29502        LIMPEZA
201076     ALIMENTOS
Name: categoria_produto, dtype: str

In [ ]:
# Conferi a frequência dos valores nas linhas do DataFrame

df_varejo_limpo.value_counts(dropna=False)

data        ID_compra  ID_cliente  genero_cliente  estado_civil  numero_filhos  classe_economica  codigo_produto  categoria_produto  nome_produto
01/02/2019  1000       534         M               4             1              C                 67              BEBIDAS            REFRIGERANTE GUARANA    1
                                                                                                  70              BEBIDAS            REFRIGERANTE OUTROS     1
                                                                                                  178             HIGIENE            LENCO UMEDECIDO         1
                                                                                                  4               ALIMENTOS          ABACAXI                 1
                                                                                                  175             LIMPEZA            LIMPADOR MULTIUSO       1
                                                                                                                                                            ..
19/08/2022  919822     155         F               2             0              B                 86              HIGIENE            PRESERVATIVO            1
                                                                                                  62              ALIMENTOS          SNACKS                  1
                                                                                                  11              ALIMENTOS          AZEITE                  1
                                                                                                  214             ALIMENTOS          CEBOLA                  1
                                                                                                  59              ALIMENTOS          SALGADINHO              1
Name: count, Length: 733447, dtype: int64

In [209]:
# Usei a lógica (if/else) para preencher as categorias com "#N/D" substituindo por "Sem Categoria""

categorias_corrigidas = []

for categoria in df_varejo_limpo["categoria_produto"]:
    if categoria == "#N/D":
        categorias_corrigidas.append("Sem categoria")
    else:
        categorias_corrigidas.append(categoria)

df_varejo_limpo["categoria_produto"] = categorias_corrigidas
df_varejo_limpo["categoria_produto"].value_counts(dropna=False)

categoria_produto
ALIMENTOS        384197
HIGIENE          137702
LIMPEZA          128632
BEBIDAS           38264
PET               28553
ACESSORIOS        12871
Sem categoria      3228
Name: count, dtype: int64

In [210]:
# Usei a lógica (if/else) para preencher as categorias com "#N/D" substituindo por "Sem Categoria" na coluna "nome_produto"

categorias_corrigidas_produto = []

for categoria in df_varejo_limpo["nome_produto"]:
    if categoria == "#N/D":
        categorias_corrigidas_produto.append("Sem categoria")
    else:
        categorias_corrigidas_produto.append(categoria)

df_varejo_limpo["nome_produto"] = categorias_corrigidas_produto
df_varejo_limpo["nome_produto"].value_counts(dropna=False)

nome_produto
PRESUNTO COZIDO          12719
SARDINHA                  6610
BANANA                    6518
ESCOVA DE DENTE           6518
GEL                       6517
                         ...
Sem categoria             3228
ABSORVENTE                3220
ALIMENTO PARA PASSARO     3198
ALHO                      3194
ALCOOL                    3168
Name: count, Length: 118, dtype: int64

In [211]:
# Conferi novamente os dados do DataFrame

df_varejo_limpo.info()
df_varejo_limpo.head()

<class 'pandas.DataFrame'>
Index: 733447 entries, 0 to 829999
Data columns (total 10 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   data               733447 non-null  str
 1   ID_compra          733447 non-null  int64
 2   ID_cliente         733447 non-null  int64
 3   genero_cliente     733447 non-null  str
 4   estado_civil       733447 non-null  int64
 5   numero_filhos      733447 non-null  int64
 6   classe_economica   733447 non-null  str
 7   codigo_produto     733447 non-null  int64
 8   categoria_produto  733447 non-null  str
 9   nome_produto       733447 non-null  str
dtypes: int64(5), str(5)
memory usage: 61.6 MB

,data,ID_compra,ID_cliente,genero_cliente,estado_civil,numero_filhos,classe_economica,codigo_produto,categoria_produto,nome_produto
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO

In [ ]:
# Ajustei os tipos de dados e verifiquei inconsistêcias

df_varejo_limpo["categoria_produto"].dtype

In [ ]:
# Conferi os tipos de dados na coluna "nome_produto"

df_varejo_limpo["nome_produto"].dtype

In [ ]:
# Conferi os tipos de dados no DataFrame

df_varejo_limpo.dtypes

data                   str
ID_compra            int64
ID_cliente           int64
genero_cliente         str
estado_civil         int64
numero_filhos        int64
classe_economica       str
codigo_produto       int64
categoria_produto      str
nome_produto           str
dtype: object

In [215]:
# Verifiquei se há questões para resolver sobre caracteres especiais, letras maiúsculas ou minúsculas, etc. nas colunas str("genero_cliente", "classe_economica", "categoria_produto", "nome_produto")

df_varejo_limpo["genero_cliente"].unique()

<StringArray>
['M', 'F']
Length: 2, dtype: str

In [216]:
df_varejo_limpo["classe_economica"].unique()

<StringArray>
['C', 'B', 'A']
Length: 3, dtype: str

In [217]:
df_varejo_limpo["categoria_produto"].unique()

<StringArray>
[      'BEBIDAS',       'HIGIENE',     'ALIMENTOS',       'LIMPEZA',
    'ACESSORIOS',           'PET', 'Sem categoria']
Length: 7, dtype: str

In [218]:
df_varejo_limpo["nome_produto"].unique()

<StringArray>
[      'REFRIGERANTE GUARANA',        'REFRIGERANTE OUTROS',
            'LENCO UMEDECIDO',                    'ABACAXI',
          'LIMPADOR MULTIUSO',           'HASTES FLEXIVEIS',
                  'MORTADELA',                     'AZEITE',
                  'AMACIANTE',                 'ENERGETICO',
 ...
                  'HAMBUGUER',      'ALIMENTO PARA PASSARO',
                     'CEBOLA',           'ENXAGUANTE BUCAL',
                      'MANGA', 'COXA E SOBRECOXA DE FRANGO',
                    'ABACATE',                      'ARROZ',
                 'ABSORVENTE',             'MOLHO BARBECUE']
Length: 118, dtype: str

# Módulo Datetime

In [219]:
# importei a classe date do módulo datetime

from datetime import date
from datetime import datetime
from datetime import timedelta

In [ ]:
# Importei o datetime

from datetime import datetime

In [221]:
# Conferi o formato e tipo de dados da coluna "data"

print(df_varejo_limpo["data"].dtype)
print(df_varejo_limpo["data"].head())

str
0    01/02/2019
1    01/02/2019
2    01/02/2019
3    01/02/2019
4    01/02/2019
Name: data, dtype: str

In [ ]:
# Converti o texto para datetime
#(Validei a regra do identificador de número de compra, convertendo a string de data da compra utilizando o módulo datetime)

df_varejo_limpo["data"] = pd. to_datetime(df_varejo_limpo["data"], dayfirst=True)

In [223]:
# Conferi a conversão

print(df_varejo_limpo["data"].dtype)

datetime64[us]

In [224]:
# Conferi se havia algum valor nulo após a conversão

df_varejo_limpo["data"].isna().sum()

np.int64(0)

In [225]:
# Conferi algumas linhas para garantir

df_varejo_limpo["data"].head()

0   2019-02-01
1   2019-02-01
2   2019-02-01
3   2019-02-01
4   2019-02-01
Name: data, dtype: datetime64[us]

In [226]:
# Conferi as informações para ter certeza

df_varejo_limpo["data"].info()

<class 'pandas.Series'>
Index: 733447 entries, 0 to 829999
Series name: data
Non-Null Count   Dtype
--------------   -----
733447 non-null  datetime64[us]
dtypes: datetime64[us](1)
memory usage: 11.2 MB

 ## Estatísticas descritivas básicas

In [227]:
# Pedi o número de linhas da coluna "numero_filhos" para iniciar a análise estatística descritiva básica proposta para o mini-projeto

len(df_varejo_limpo["numero_filhos"])

733447

In [228]:
# Verifiquei a quantidade de clientes únicos 

df_varejo_limpo["ID_cliente"].nunique()

1000

In [229]:
# Agrupei um único número de filhos por cliente usando o groupby() e o first() 

df_filhos = df_varejo_limpo.groupby("ID_cliente")["numero_filhos"].first()

In [230]:
# Contei os clientes por número de filhos usando value_counts() ordenando com sort_index()

df_filhos.value_counts().sort_index()

numero_filhos
0    527
1    125
2    130
3    121
4     97
Name: count, dtype: int64

In [231]:
# Usei o describe() para gerar estatísticas descritivas (média; mediana; desvio padrão; máximo; mínimo; e contagem, quartis)

df_filhos.describe()

count    1000.00000
mean        1.13600
std         1.41333
min         0.00000
25%         0.00000
50%         0.00000
75%         2.00000
max         4.00000
Name: numero_filhos, dtype: float64

In [232]:
# Usei mode() para obter a moda

df_filhos.mode()

0    0
Name: numero_filhos, dtype: int64

In [233]:
# Para melhor visualização, fiz a mesma operação com print()

print("Estatísticas do número de filhos por cliente:")
print("Contagem:", df_filhos.count())
print("Média:", df_filhos.mean().round(2))
print("Mediana:", df_filhos.median().round(2))
print("Moda:", df_filhos.mode().tolist())
print("Desvio padrão:", df_filhos.std().round(2))
print("Mínimo:", df_filhos.min())
print("Máximo:", df_filhos.max())
print("Quartis:")
print(df_filhos.quantile([0.25, 0.50, 0.75]))

Estatísticas do número de filhos por cliente:
Contagem: 1000
Média: 1.14
Mediana: 0.0
Moda: [0]
Desvio padrão: 1.41
Mínimo: 0
Máximo: 4
Quartis:
0.25    0.0
0.50    0.0
0.75    2.0
Name: numero_filhos, dtype: float64

# Padrões de agrupamento

In [ ]:
# Conferi o DataFrame 

df_varejo_limpo

,data,ID_compra,ID_cliente,genero_cliente,estado_civil,numero_filhos,classe_economica,codigo_produto,categoria_produto,nome_produto
0,2019-02-01,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA
1,2019-02-01,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS
2,2019-02-01,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO
3,2019-02-01,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
4,2019-02-01,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO
...,...,...,...,...,...,...,...,...,...,...
829991,2022-08-19,919822,155,F,2,0,B,86,HIGIENE,PRESERVATIVO
829993,2022-08-19,919822,155,F,2,0,B,62,ALIMENTOS,SNACKS
829994,2022-08-19,919822,155,F,2,0,B,11,ALIMENTOS,AZEITE
829998,2022-08-19,919822,155,F,2,0,B,214,ALIMENTOS,CEBOLA
829999,2022-08-19,919822,155,F,2,0,B,59,ALIMENTOS,SALGADINHO

In [235]:
# Contei os registros de compra combinando a categoria do produto com o número de filhos

df_varejo_limpo.groupby(
    ["numero_filhos", "categoria_produto"]
).size()

numero_filhos  categoria_produto
0              ACESSORIOS             6755
               ALIMENTOS            201670
               BEBIDAS               19991
               HIGIENE               72302
               LIMPEZA               67625
               PET                   14960
               Sem categoria          1683
1              ACESSORIOS             1564
               ALIMENTOS             47613
               BEBIDAS                4901
               HIGIENE               17018
               LIMPEZA               15782
               PET                    3561
               Sem categoria           406
2              ACESSORIOS             1647
               ALIMENTOS             49269
               BEBIDAS                4895
               HIGIENE               17647
               LIMPEZA               16583
               PET                    3721
               Sem categoria           406
3              ACESSORIOS             1689
               ALIMENTOS             48284
               BEBIDAS                4812
               HIGIENE               17487
               LIMPEZA               16148
               PET                    3587
               Sem categoria           400
4              ACESSORIOS             1216
               ALIMENTOS             37361
               BEBIDAS                3665
               HIGIENE               13248
               LIMPEZA               12494
               PET                    2724
               Sem categoria           333
dtype: int64

In [236]:
# Calculei a categoria com maior percentual de compras para cada número de filhos

print(preferencia.idxmax(axis=1))

numero_filhos
0    ALIMENTOS
1    ALIMENTOS
2    ALIMENTOS
3    ALIMENTOS
4    ALIMENTOS
dtype: str

In [237]:
# Pedi para organizar em ordem descrescente para visualizar primeiro as categorias mais frequentes e o total de vendas 

df_varejo_limpo.groupby(
    ["numero_filhos", "categoria_produto"]
).size().sort_values(ascending=False)

numero_filhos  categoria_produto
0              ALIMENTOS            201670
               HIGIENE               72302
               LIMPEZA               67625
2              ALIMENTOS             49269
3              ALIMENTOS             48284
1              ALIMENTOS             47613
4              ALIMENTOS             37361
0              BEBIDAS               19991
2              HIGIENE               17647
3              HIGIENE               17487
1              HIGIENE               17018
2              LIMPEZA               16583
3              LIMPEZA               16148
1              LIMPEZA               15782
0              PET                   14960
4              HIGIENE               13248
               LIMPEZA               12494
0              ACESSORIOS             6755
1              BEBIDAS                4901
2              BEBIDAS                4895
3              BEBIDAS                4812
2              PET                    3721
4              BEBIDAS                3665
3              PET                    3587
1              PET                    3561
4              PET                    2724
3              ACESSORIOS             1689
0              Sem categoria          1683
2              ACESSORIOS             1647
1              ACESSORIOS             1564
4              ACESSORIOS             1216
1              Sem categoria           406
2              Sem categoria           406
3              Sem categoria           400
4              Sem categoria           333
dtype: int64

In [238]:
# Verifiquei a relação entre número de filhos e o nome do produto

df_varejo_limpo.groupby(
    ["numero_filhos", "nome_produto"]
).size().sort_values(ascending=False)

numero_filhos  nome_produto
0              PRESUNTO COZIDO          6668
               SARDINHA                 3534
               CEBOLA                   3470
               LIMPADOR PERFUMADO       3464
               PAPINHA INFANTIL         3453
                                        ...
4              AGUA SANITARIA            310
               ABACAXI                   297
               ALIMENTO PARA PASSARO     294
               ABSORVENTE                278
               ALCOOL                    270
Length: 590, dtype: int64

In [239]:
# Calculei a proporção de clientes de cada grupo que comprou cada categoria

'''
Criei uma tabela com pivot_table() cruzando duas variáveis - número de filhos e categoria do produto;
Usei index para colocar o número de filhos nas linhas;
Coloquei a categoria do produto na coluna com columns;
Usei o aggfunc= "size" para contar os registros em cada combinação filhos-categoria;
Pedi para colocar o número zero quando não houvesse registro com fill_value = 0. 


'''
tabela = df_varejo_limpo.pivot_table(
    index = "numero_filhos",
    columns = "categoria_produto",
    aggfunc = "size",
    fill_value = 0
)

preferencia = tabela.div(tabela.sum(axis=1), axis=0) * 100

print(preferencia.round(2))

categoria_produto  ACESSORIOS  ALIMENTOS  BEBIDAS  HIGIENE  LIMPEZA   PET  \
numero_filhos
0                        1.75      52.38     5.19    18.78    17.57  3.89
1                        1.72      52.41     5.39    18.73    17.37  3.92
2                        1.75      52.32     5.20    18.74    17.61  3.95
3                        1.83      52.25     5.21    18.92    17.47  3.88
4                        1.71      52.59     5.16    18.65    17.59  3.83

categoria_produto  Sem categoria
numero_filhos
0                           0.44
1                           0.45
2                           0.43
3                           0.43
4                           0.47